---
# value file for openweather-exporter helm chart

image:
  repository: billykwooten/openweather-exporter
  tag: "0.0.14"

env_vars: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

ow:
  port: "9091"
  degreesUnit: C
  language: EN
  cacheTTL: "180"
  enablePol: "true"
  enableUv: "true"
  interval: 2m
