global:
  nodeSelector:
    kubernetes.io/os: linux
  rbac:
    create: true
    aggregateClusterRoles: true
  podSecurityPolicy:
    enabled: false
  logLevel: 2
  leaderElection:
    namespace: "kube-system"

crds:
  enabled: true
  keep: true

replicaCount: 1

resources:
  requests:
    cpu: "2m"
    memory: "37Mi"
  limits:
    cpu: "50m"
    memory: "128Mi"

podAnnotations:
  match-regex.version-checker.io/cert-manager: 'v(\d+)\.(\d+)\.(\d+)'

extraArgs:
  - --acme-http01-solver-nameservers=10.0.0.10:53

prometheus:
  enabled: true

webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: "1m"
      memory: "43Mi"
    limits:
      cpu: "50m"
      memory: "128Mi"
  podAnnotations:
    match-regex.version-checker.io/cert-manager: 'v(\d+)\.(\d+)\.(\d+)'

cainjector:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: "2m"
      memory: "19Mi"
    limits:
      cpu: "50m"
      memory: "64Mi"
  podAnnotations:
    match-regex.version-checker.io/cert-manager: 'v(\d+)\.(\d+)\.(\d+)'

acmesolver:
  image:
    repository: quay.io/jetstack/cert-manager-acmesolver

startupapicheck:
  enabled: true