---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kanboard.fullname" . }}
  labels:
    {{- include "kanboard.labels" . | nindent 4 }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
    {{- range $key, $value := .Values.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "kanboard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kanboard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kanboard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.additionalSpec }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.kanboard.plugin_installer }}
            - name: PLUGIN_INSTALLER
              value: {{ .Values.kanboard.plugin_installer | quote }}
            {{- end }}{{- if .Values.kanboard.plugin_installer }}
            - name: DATABASE_URL
              value: {{ .Values.kanboard.databaseUrl | quote }}
            {{- end }}
            {{- if .Values.kanboard.debug }}
            - name: DEBUG
              value: {{ .Values.kanboard.debug | quote }}
            {{- end }}
            {{- if .Values.kanboard.apiAuthenticationToken }}
            - name: API_AUTHENTICATION_TOKEN
              value: {{ .Values.kanboard.apiAuthenticationToken | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /login
              port: http
            timeoutSeconds: 180
            periodSeconds: 300
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /login
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
          - mountPath: /var/www/app/data
            name: data
            subPath: data
          - mountPath: /var/www/app/plugins
            name: data
            subPath: plugins
          - mountPath: /etc/nginx/ssl
            name: data
            subPath: ssl
          {{- end }}
          {{- if .Values.kanboard.customConfig }}
          - mountPath: /var/www/app/data/config.php
            name: custom-config
            subPath: config.php
          {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "kanboard.fullname" . }}-data
        {{- end }}
        {{- if .Values.kanboard.customConfig }}
        - name: custom-config
          configMap:
            name: {{ .Values.kanboard.customConfig }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
