apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "booklore.fullname" . }}
  labels:
    {{- include "booklore.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "booklore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "booklore.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "booklore.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              #protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "booklore.fullname" . }}-app-config
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.auth.existingSecret }}
                  name: {{ .Values.mariadb.auth.existingSecret }}
                  {{- else }}
                  name: {{ .Release.Name }}-mariadb
                  {{- end }}
                  key: mariadb-password
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if (or .Values.persistence.dataVolume.enabled .Values.persistence.booksVolume.enabled .Values.extraVolumeMounts) }}
          volumeMounts:
            {{- if .Values.persistence.dataVolume.enabled }}
            - name: data
              mountPath: /app/data
            {{- end }}
            {{- if .Values.persistence.booksVolume.enabled }}
            - name: books
              mountPath: /books
              {{- with .Values.persistence.booksVolume.subPath }}
              subPath: {{ . | quote }}
              {{- end }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
        {{- if and .Values.mariadb.enabled .Values.mariadb.inline }}
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-mariadb-env
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.auth.existingSecret }}
                  name: {{ .Values.mariadb.auth.existingSecret }}
                  {{- else }}
                  name: {{ .Release.Name }}-mariadb
                  {{- end }}
                  key: mariadb-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.auth.existingSecret }}
                  name: {{ .Values.mariadb.auth.existingSecret }}
                  {{- else }}
                  name: {{ .Release.Name }}-mariadb
                  {{- end }}
                  key: mariadb-password
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mariadb-config
              mountPath: /config
        {{- end }}
      {{- if (or .Values.persistence.dataVolume.enabled .Values.persistence.booksVolume.enabled .Values.extraVolumes (and .Values.mariadb.enabled .Values.mariadb.inline .Values.mariadb.persistence.config.enabled)) }}
      volumes:
        {{- if .Values.persistence.dataVolume.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.dataVolume.existingClaim }}
              {{- .Values.persistence.dataVolume.existingClaim }}
            {{ else }}
              {{- include "booklore.fullname" . }}-data
            {{- end }}
        {{- end }}
        {{- if .Values.persistence.booksVolume.enabled }}
        - name: books
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.booksVolume.existingClaim }}
              {{- .Values.persistence.booksVolume.existingClaim }}
            {{ else }}
              {{- include "booklore.fullname" . }}-books
            {{- end }}
        {{- end }}
        {{- if and .Values.mariadb.enabled .Values.mariadb.inline .Values.mariadb.persistence.config.enabled }}
        - name: mariadb-config
          persistentVolumeClaim:
            claimName: {{ if .Values.mariadb.persistence.config.existingClaim }}
              {{- .Values.mariadb.persistence.config.existingClaim }}
            {{ else }}
              {{- include "booklore.fullname" . }}-mariadb-config
            {{- end }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
