{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mariadb-env
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  PUID: {{ .Values.mariadb.env.PUID | quote }}
  PGID: {{ .Values.mariadb.env.PGID | quote }}
  TZ: {{ .Values.mariadb.env.TZ | quote }}
  MYSQL_DATABASE: {{ .Values.mariadb.auth.database | quote }}
  MYSQL_USER: {{ .Values.mariadb.auth.username | quote }}
{{- end }}
