{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-mariadb
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-mariadb-env
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.auth.existingSecret }}
                  name: {{ .Values.mariadb.auth.existingSecret }}
                  {{- else }}
                  name: {{ .Release.Name }}-mariadb
                  {{- end }}
                  key: mariadb-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.auth.existingSecret }}
                  name: {{ .Values.mariadb.auth.existingSecret }}
                  {{- else }}
                  name: {{ .Release.Name }}-mariadb
                  {{- end }}
                  key: mariadb-password
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mariadb-config
              mountPath: /config
      volumes:
        - name: mariadb-config
          persistentVolumeClaim:
            claimName: {{ if .Values.mariadb.persistence.config.existingClaim }}
              {{- .Values.mariadb.persistence.config.existingClaim }}
            {{ else }}
              {{- include "booklore.fullname" . }}-mariadb-config
            {{- end }}
{{- end }}
