{{- if not .Values.mariadb.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  mariadb-password: {{ .Values.mariadb.auth.password | quote }}
  mariadb-root-password: {{ .Values.mariadb.rootPassword | quote }}
{{- end }}
