apiVersion: v1
kind: Service
metadata:
  name: {{ include "booklore.fullname" . }}
  labels:
    {{- include "booklore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.mariadb.enabled }}
    - port: {{ .Values.mariadb.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    {{- end }}
  selector:
    {{- include "booklore.selectorLabels" . | nindent 4 }}
