# Default values for booklore.
---
mariadb:
  enabled: true
  # Run MariaDB inside the app pod (inline) instead of a separate StatefulSet
  inline: true
  port: 3306
  image:
    repository: lscr.io/linuxserver/mariadb
    tag: "11.4.8"
    pullPolicy: IfNotPresent
  auth:
    database: booklore
    username: booklore
    password: ""
    existingSecret: "booklore-db-secret"
  rootPassword: ""
  env:
    PUID: "1000"
    PGID: "1000"
    TZ: "Europe/Warsaw"
  persistence:
    config:
      enabled: true
      size: 1Gi
      existingClaim: "booklore-mariadb-config"

image:
  repository: ghcr.io/booklore-app/booklore
  pullPolicy: IfNotPresent
  tag: "v1.18.5"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 568

securityContext: {}
  # readOnlyRootFilesystem: false
  # runAsNonRoot: true
  # runAsUser: 568
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #     - ALL

service:
  type: ClusterIP
  port: 6060
  targetPort: http

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: booklore.shpaq.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - booklore.shpaq.org
      secretName: booklore-shpaq-org-tls
  extraPaths: []

resources:
  limits:
    cpu: 1500m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  tcpSocket:
    port: http
readinessProbe:
  tcpSocket:
    port: http

persistence:
  dataVolume:
    enabled: true
    size: 2000Mi
    existingClaim: "booklore-data"
  booksVolume:
    enabled: true
    size: 10Gi
    existingClaim: "media"
    subPath: "library/books"

extraVolumes:
  - name: bookdrop
    hostPath:
      path: /data/media/downloads/transmission/complete
      type: Directory

extraVolumeMounts:
  - name: bookdrop
    mountPath: /bookdrop
    readOnly: false

nodeSelector:
  kubernetes.io/role: worker

tolerations: []

affinity: {}
