---
# Default values for whoops.

replicaCount: 1

image:
  repository: szpaczyn/whoops
  pullPolicy: Always
  tag: 0.2.4

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  host: whoops.shpaq.org
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-secret: whoops-auth

