{{- if .Values.hpa.enabled -}}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "name" . }}-cpu
  labels:
    chart: {{ .Chart.Name}}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "name" . }}
  minReplicas: 1
  maxReplicas: {{ .Values.hpa.limit | default 2}}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: 256M
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "name" . }}-memory
  labels:
    chart: {{ .Chart.Name}}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "name" . }}
  minReplicas: 1
  maxReplicas: {{ .Values.hpa.limit | default 2}}
  targetCPUUtilizationPercentage: 100
{{- end }}
