env:
    DATABASE_URL: ENC[AES256_GCM,data:3T4HWBFzz/w2qpBgzL4EW1vX8/UcRzZXrpuvv4YiwzwiI1sh6nYMS3uyT+frhhk3UIo/tRWVY7xrVAI0r4qQodVIpIOw4IOR9KgTFmqBk6taU1bcOXVdo9znZyVBqfGCumTj,iv:5GH4Ap163Qh0B+fv8n+GEAMWviWGaAoFllFZOZhrOYA=,tag:eheUlnUB/iT1eAu7WBmZBQ==,type:str]
    SIGNUPS_ALLOWED: ENC[AES256_GCM,data:4i++S8I=,iv:DgXUGyBGWYNCb4wKdHycfk9nq1OAvF8AgVXNoRC5r4I=,tag:155F3xPvK4Jqu8p9XtOe8A==,type:bool]
    INVITATIONS_ALLOWED: ENC[AES256_GCM,data:RkFflw==,iv:PrVCvRhe6u4ANlsWjHU8GEgRU8Xrgv83bwxyFXGggZ8=,tag:/nh1OIt+/vC+2V/JZKUR0Q==,type:bool]
    ADMIN_TOKEN: ENC[AES256_GCM,data:9M5RIpV2Gzl8R6XkLvheZOB5fGdPRayI0+yR6RbLGpqSXOee6SqkpHmOIty9GXVtICpj6o8Z7ZtFC3DYQfnzMKMJdsDI5kp6yGVHitDiwZgtv2a08gPOmlFWGdQwOj+sKfvwKYkfCvKPn3EySfFZx0tR6gwUWMnEsYGH9CPckN2vs7d2HCIeforPeg==,iv:ZR+mfHGjI5nDCTogpRxs9lQ4OBLodY9E9UPRwDsJgeg=,tag:Okc7g5ID1xx7EoDZlmf8PQ==,type:str]
    #ENC[AES256_GCM,data:Q5vMTleDd9BDbQHlr6AyvUNca6Sr4cOEEFBmSTBLumobx71RwaJibmiX/kNP6/HtM57HLHeUTGQpp1TrFemCWjM=,iv:KSg9u/ccELSTO2DXBo3RZuuAone4SIxa9XReQLo0JPg=,tag:YX2Lv3AbIwwA7FmRMkUyMA==,type:comment]
    SERVER_ADMIN_EMAIL: ENC[AES256_GCM,data:PO7I1BpKqQLQ+qsTHMDY,iv:ZgTdHZBO5CnMnGFHn6FpWic/WEQOTQ5+DEHoQxdIgiA=,tag:IewkReu24eUUhAcJjLSCcA==,type:str]
    DOMAIN: ENC[AES256_GCM,data:xLQDonXSpwx4KzFyYJRP2ILKYgrjMQepk3Ft,iv:E8haIk9ubCMezxVFuN1Lp5DUimRORl/3LNSGhDSGcQ0=,tag:J0NG2nZF7FPquYfVB/pJQQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:mDxiA0YhjyAag0LNPJc=,iv:4h9o16w7BFrYyXbJ0qRm+jtt4B35PLQO9dEjMOFCYTk=,tag:zprWxovoEA9+JfXV3/xE1A==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:vQnLw7WL3xXM6UHt7YC08WJU,iv:QI9/aKfD1IZ/PN77PPLZBtECPKzm4A2GK7zlWQCMYJs=,tag:C6SuWx1JaIQZCBYqi0iRJQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:Q2K9,iv:Fy0qnN8Uuf/uIPxyXc+9NHdGKJ35ExmdD3R4Jr7U4Yk=,tag:x5O8TXsIcdKC9AsstfgwwA==,type:int]
    #ENC[AES256_GCM,data:dbMpG/OZnnNkj+7tqT8w+w0s,iv:fhvEqFIJbP2+WV0s7r5Hq2dcff0j251LV7Ab7AdO3DY=,tag:9K413OZBwfqCzVp9EfmtCw==,type:comment]
    SMTP_SECURITY: ENC[AES256_GCM,data:uh2lAT49l9I=,iv:MzkLdzx4Yw0ZCkKpgfqQGXNX+FDDp1R+QydZJdmU/CA=,tag:VMUt6kTuY31LqCs7GAJBgw==,type:str]
    SMPT_FROM_NAME: ENC[AES256_GCM,data:6CQidxVRkR92OfWYdX2OxhH8MVXC/x7LkLuX,iv:ScxZm8Ut3D2ntofmmyVNPA5qcue4PhQ+fG8qWnOX/tY=,tag:8gPfbLiHemvzb+PfjSV9ZQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:qgx8ZGaEleOFj+MQGruU,iv:RrTpYmbIEmZiHxWClFv6WIxTVkTnhmdjaebTtKpuSw8=,tag:OgKyBYag5FMV1tB0q7wrKw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:xTdxyuClASI5awtVjraDig==,iv:tOGx7wtSIAbQg00y/XLG4XX+YAfSVIf/53kdsqHHj5o=,tag:wVp1YGeV1/dpjPbxcVKGBQ==,type:str]
    WEB_VAULT_ENABLED: ENC[AES256_GCM,data:Qikd8A==,iv:h9Aa7gEjzfsmvhuk2fGzn8lc7RHqTOusgMkUeOzXg+E=,tag:NkEMSDEvzHXPq3hZ0lV/0A==,type:bool]
    EXTENDED_LOGGING: ENC[AES256_GCM,data:TH700g==,iv:M/rHW0bGScFeqw+QNGnoxBvEjcK6YLL85CNX8KTdTw8=,tag:C9IXa6sikFTzcW9oEKZyNQ==,type:bool]
    LOG_LEVEL: ENC[AES256_GCM,data:1UAYsw==,iv:805366mHWHZMy2hKvfDVMtubBti8s3EKGrLqy/vCKOk=,tag:ps5k1Smh8U37ota9VU/sFg==,type:str]
    #ENC[AES256_GCM,data:Kc9qcgSQ7l77SQlwaVEbDW8PRQ8BbDSwQwOL9MIwnjUUXrbrLSAlGY/9ARWRcBfOMYeg/tB/f25NkYj7E9yqph82wuFpWlr+N2RfpgUYKBFFO3gj7SO9rxcbgTU3+6MF6ePcF7UqEDqQ2xDzHZo4p49gWNos1h0IBCdBwRrpmFgsvr+Slv0Ymg==,iv:hRJ2ZrcjczBVDWIDn+17cD2+Am5qmilXkynOgEkNA98=,tag:x5EjA4fT/tWFrsFreoaZEw==,type:comment]
sops:
    lastmodified: "2026-01-24T10:21:15Z"
    mac: ENC[AES256_GCM,data:q/CgLkLq8XiJm90gSrKACsGA4UczkJdekhY0FetJmAiMo31nqa8HcbHjXiNiC64/BDGeH8+IHUUHmqOyppNIJCFMBowkcjDohCpFCYH+4VXmx6yc3N41ZRqDss+p85MpTqJSi0oUks81b0WcsFapy14LbzZ8NgSKXdjMVq2Df+Y=,iv:hYMmuwr1fcY3N2c8XzaLk9lkajIIAk5wiQMD3AFP0WE=,tag:I20m3EzXHnLm4TPTTCYrMQ==,type:str]
    pgp:
        - created_at: "2021-04-27T07:42:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ//Z4AZYHoz2xNuHPRXvQOk8Etyh/KGbNCezTWlpGNlbmP+
            rbYZEGhkLiObf7QkmhkfsfqvPUQpRzuzxjYRBD8PUyCjkKhr76cu3C5XZfD6p+DA
            qcSFsQyEFJOHoD5bvEI45D7XxudR11ylX0PqeTdnsN2DYBhPDiMKI8KuKq6eOZoh
            2PvMa5kqo7Risppm8ZLCVExTKJoSjm421w9PdbfWneZV2wbEwI6OD8yN+ESbIrgt
            8dfG7Pm6xJcJYNbj75Lur1IM9GAjJcKP5exBcpPKuUME+1hLEs714ve9DktGfu0Q
            i6jz1m6rjb+yRclUUYDFlvQMoK1Md6AZmXTi96VhM3VXOB3JaRDm5Y+XqNO9Pk3T
            4XmoEX6iUW7uQc9z99dVBaMm2ssgS1I2WJ9ywwyaMsOCzOQNCFPPz8sXB7jMEmco
            P/sIxTN40OtIjQ7cTvTCQ6fCJUoma6hRDYxAH4ExWGcVtKV8lov6e3EN6gucM1xq
            kTN/3NUinUNnV7w27h11+eL6zLck5K/+xS4SGYjEa7Kzm8fhymf7jyFM1vYjRkoe
            k8+9iNl7n70W5uaHxD7ZE6Ofrm24iFutOKp+weV72Qb2sXqPclmHqUO49xqQqU3N
            kT5jCTRmeEfUXZKvLeFo6megMuCogUQhU25lTrt+vvgJHDngfgjADdbbawabdBzS
            XgGtTTMg4ufKOABZGVwClcDuydgCw8QQdDT4Y9zZo+GimBD59xd3ZiK1FDKf3oS3
            zBuOkrCumfOTw/5Zcl2Dmna665iFwyeD6STW0L8aiIfYEZ9oV5gj1/3I0FcJV9s=
            =V9WJ
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
