#ENC[AES256_GCM,data:sDGiJyHE1K5sy7FumBGhdAoG/WWDmbb7+Bn7,iv:NnLZSiMUqPdpTE5S0pQNLdIx9uFqoxoTZsHouH8vJLU=,tag:YCtXXEC02zX5VFqu4+j9/w==,type:comment]
gitea:
    admin:
        username: ENC[AES256_GCM,data:aa67E6U=,iv:jHfuzqh/kBqSOpPiWJsZ4WQnCp4P6wSc/cyN8Bci2Vg=,tag:WbUA1FmgCngBvkd+HLWu0w==,type:str]
        password: ENC[AES256_GCM,data:lmQzb+ydid7VRx3TnxtHDdOSIq1PYudki8wGpmSvRZ4=,iv:qlXTHMbP0VtHNeIdJnwqFnAuOtDSmYv9O+/MGXXDEVY=,tag:neDnLzvNiah3Vizp1eR20g==,type:str]
        email: ENC[AES256_GCM,data:MS0UvxelJE5d4Dg2QzLQ,iv:bh9yg/RllHWPhoZP1ezR69fk/vvm0kECJBY9Qi7Zf2s=,tag:PXHQvsIXYCzWKUVQby9pRA==,type:str]
    config:
        RUN_MODE: ENC[AES256_GCM,data:6Lmc+w==,iv:Geiv4T6xD+xvqmBLhQnage61Q4QN57J3SprrATSC3YY=,tag:imxJoFSLxhSJ9YrT8I6nUw==,type:str]
        APP_NAME: ENC[AES256_GCM,data:5eed2WFH1Kyw3uayW3RresXn/LGM,iv:9F1e4MWNgV+b/DswmHEUPAlesUl8fbgAGETfmVKpZi0=,tag:W4r5+eM/RwW/4jNlZSK7jg==,type:str]
        ui:
            DEFAULT_THEME: ENC[AES256_GCM,data:pz3tKz4TD5BMHQ==,iv:A0HBdRgFp38YAxNCmUeMfPeXWgvqvs+ILeKM2rlKoP0=,tag:ADPEnQ5KkMupE7YDzemkkQ==,type:str]
            THEMES: ENC[AES256_GCM,data:mu7qIVJNK8rD2A==,iv:RoxdF6MsjQ4pEQFMD2lBEcxcKqvIfSzCEwZEPZylDZ0=,tag:MUaGYv4sE/DpGpFFUES6GQ==,type:str]
        ui.meta:
            AUTHOR: ENC[AES256_GCM,data:yVDrCRa8VtQd8gUg/QgT,iv:lXu36jmkXy8Z2d9TQ6eM59/ujGel0c+QnpG2y7gOxfo=,tag:Fcx3t3c3vlYlBo0hoWflKA==,type:str]
        server:
            ROOT_URL: ENC[AES256_GCM,data:bP2rqx3/nUCz7QhhEYgvoTc1/0PqjYA=,iv:GvBR2rOC/0iCqaA0avcINmKeCHRW+yl1fkfbyoIxt3k=,tag:5Tx9Njunv8M1anFxwsw6+A==,type:str]
            SSH_ROOT_PATH: ENC[AES256_GCM,data:0jo4xB8QUx/Rj4SlTp0=,iv:xebpUQ+ssHZqHoZnZXIEg7IYYic88b5fSipHoEqr48o=,tag:5yVZTTPeijIywxne1TyR+Q==,type:str]
            SSH_EXPOSE_ANONYMOUS: ENC[AES256_GCM,data:zXm5dg==,iv:dqL9vhOkP3UbCfaSqrrQDzcuuCsNdUIfJqXzJF7nMcY=,tag:XxAAWSI/uRKJ8wpeIoeqQg==,type:bool]
            LFS_START_SERVER: ENC[AES256_GCM,data:fzE1BQ==,iv:3DBxQDgzczMtuLcfFvliadhF/w+azGI6rZqRmM3euPg=,tag:le9tYfxtC5Pq5Fb4s0yrVg==,type:bool]
            SSH_DOMAIN: ENC[AES256_GCM,data:afh+NBcgcKCR1TnCaEM=,iv:3FnIqEPYp71g2qvpdL12jbtYiPlxVXnz2JuktrTNJy0=,tag:kgtTz2eAP6KwdHlE63PvkQ==,type:str]
            SSH_PORT: ENC[AES256_GCM,data:b0I=,iv:e76+2YhyHfaiP5Wvf1ZRTAcc2vgj1jhYVUtvaXPjTKo=,tag:7jH6KQcATHBa9RPa1aqJ5w==,type:int]
        other:
            SHOW_FOOTER_BRANDING: ENC[AES256_GCM,data:jKukkg==,iv:NlSWgOLvCYmYcJOeNm0FKY23CZvU4xINcbDjVv9aueE=,tag:fqLFyFwFQ+tjys2qjbtRdw==,type:bool]
        time:
            DEFAULT_UI_LOCATION: ENC[AES256_GCM,data:8i/h0U5L6e1Ci24npw==,iv:0BmQm1psu1Ubyq5RkdgOxFtiU2cG7I1KtD6ruspfPHI=,tag:HZeF20cqKGE+tOuPXb3x/g==,type:str]
        database:
            DB_TYPE: ENC[AES256_GCM,data:0nOZ2Al2/r4=,iv:1psioMoX4fQ6ASHj5/lErEPmmy4rwPOUqY/1OtV8haU=,tag:lUDGBWE3+LxMIoRVf5K2cA==,type:str]
            HOST: ENC[AES256_GCM,data:8bPnu5h1jrSdjGaDv14Jcli7BVDMapddXspA3kIIvx/GM/c=,iv:VaWLVrCdca5YCy/cWVNDiYoajyFuJYFYK39QtlYhUUU=,tag:y8N29oazX274zaRg42vNZQ==,type:str]
            NAME: ENC[AES256_GCM,data:hXevsmI=,iv:YJAYtCdV40QFRH8KHIcUcwv6txQ2ys91GdtZ80F4jVQ=,tag:XIFwebg9VSIXR4UCCZG7gw==,type:str]
            USER: ENC[AES256_GCM,data:PDxRNJA=,iv:+tQMLlxAfI9Wy+RaPVUhLzexmOI1GhEmF/Bvh2mG4eg=,tag:Ei/2nth0HFIKDn83D6YYKw==,type:str]
            PASSWD: ENC[AES256_GCM,data:/4B1AE3f5m6grBF4eBMpDmC4UDHlhA1I1OGHNPjXc9E=,iv:kz9ctDnJLmy9YaKI/TpyTcMiSuvQPQHGIUcbU3iaAD0=,tag:DyOCAAJKzAG6ySRoaJd0Fg==,type:str]
            SCHEMA: ENC[AES256_GCM,data:6xr+p+/r,iv:XRQJDsjavlUgN8bRXoe9PGRkZUG6yn/V9sL6dPq1YsU=,tag:WgaOqMO8kVGL3uxUDfYzhw==,type:str]
            LOG_SQL: ENC[AES256_GCM,data:2e5FWD4=,iv:FHn9rBH2FBeul9aDwF9oaOxCRe/hJNZMhN1jXOD441k=,tag:k7+9svVHCfSpgS3P5g/wFA==,type:bool]
        log:
            MODE: ENC[AES256_GCM,data:qGC8XC49Uw==,iv:1zsrcJbjfUtr7tW+7S/lqPRMdmOKkU+La1iTdeKACaU=,tag:8FbJfWlf0rT7PCxBoy87Rw==,type:str]
            #ENC[AES256_GCM,data:SjtHb7WnFGBK5PvTGpOkLX/OjwRby2aB,iv:Mtj+W89E5iqmZhe7cMUyvMyCo9zbeahd1vQNNITIkAM=,tag:mF/Wgzn+JnbJze8/b6exLw==,type:comment]
            LEVEL: ENC[AES256_GCM,data:9zWAkg==,iv:Yv4oYIcSct0flcA87WP0ZemZ7wpF6dk5K6eOWdjdig4=,tag:mI+PLjUcJWjA0dZzpONFng==,type:str]
            #ENC[AES256_GCM,data:Mhy+8Lxnviof5dczFjXXX2R4FC3A,iv:R0ypKW41pyDmxDNqxskfEJQqYhcxAq+KkyMk/eelsO8=,tag:R0Z8HuXafM7nxMLAnC7/FA==,type:comment]
            #ENC[AES256_GCM,data:QPkq8h20wTy2l80l3sIX+Q==,iv:VuUvaQ5qAXZglqqGB8+yJLy9VmdtsmB6eBtGyLveaW8=,tag:GNfculZRaSZMhnyWfl+dMA==,type:comment]
            STACKTRACE_LEVEL: ENC[AES256_GCM,data:NBNqEg==,iv:SBugp2QINISWBmdwL6afPl6mfuZoQrMk5vtkw1Tgwbc=,tag:oMHuDMabDEzO7ZJIxv8VVg==,type:str]
        log.console:
            MODE: ENC[AES256_GCM,data:popfwpZ4AQ==,iv:nROS4KNJ7RYcp+Ua27/vvRSw33XHtvQgCWDqPGUpKcs=,tag:z3yAOplbDs6UeU3ksJa2Kw==,type:str]
            LEVEL: ENC[AES256_GCM,data:RVy+wg==,iv:1gMqhuCxsxlJ9iyrcy4sCoCojR48J0htfbrjfr3iIuA=,tag:4delOjnjrIR0POlFkY+TCA==,type:str]
            STACKTRACE_LEVEL: ENC[AES256_GCM,data:9oOeIQ==,iv:hG/B5i5qkJD5IS/Ui1lwxDyh5SecrX3/BgDtjgrrMd4=,tag:kXlc5GAv2mQBz2z8JcrmKw==,type:str]
            FLAGS: ENC[AES256_GCM,data:3Wz5GaB/4Vs=,iv:LiVYcJV3fniGvWyv+9A+uTKNRsH1bUNaFvrFmjZd0V4=,tag:BxJrqxwKrQme1EeN1MNZig==,type:str]
            #ENC[AES256_GCM,data:99nswheOmMFV+roBhgkDJqVTePwf5RMO+SphTmnCCTrNN5OwUOre/We2jzEdqWQ=,iv:j94i3CfZ7uM0lbTOUUJQXHGwi+KvR30R7v0MwUSpI0w=,tag:jb3OaBHkxMDyGb87uuaBlw==,type:comment]
            COLORIZE: ENC[AES256_GCM,data:zTOLvA==,iv:32LmcwkRBTyP2kiu8xejmCgjF0v+pc6aHPBMFXYaC9U=,tag:+X1OwNSdEjP+AIOgGZrTuw==,type:bool]
        log.console.router:
            LEVEL: ENC[AES256_GCM,data:L6ytRQ==,iv:mUM3RRU/QIDLV0WbUuRIToCUWEKwAuhIG+w+lfnI4q8=,tag:vhpvfQyIKVPlnqmaGLwzAA==,type:str]
        log.console.access:
            LEVEL: ENC[AES256_GCM,data:C1E9uw==,iv:HR0ZGd8ZNdNLp3M5s3S2bf3PM5FzD+qqJYsHK+q9E7Y=,tag:bBjMS1bg09lp5frmCTSQmQ==,type:str]
        attachment:
            ENABLE: ENC[AES256_GCM,data:cq7YfQ==,iv:xARQG4qP7oT4p/PWokJr3SMT3UpHUTNrMrtNhXpcrIs=,tag:Kv+QAq9KbEm6FONKnogZGw==,type:bool]
            MAX_SIZE: ENC[AES256_GCM,data:/FVUk6ba,iv:8YQJermM1ZGMAtu9n0OEPoQMwJzBpMhNICDOVeHEtrU=,tag:WYWxgbwtd9GWzXJ+4z4w6g==,type:int]
            MAX_FILES: ENC[AES256_GCM,data:BYFJ,iv:etxQVx9/5Hqps6VAsCNU3oGoCTYvQg5EvAZMbNHNfYQ=,tag:7dHnlrlDoCnrp/aFxrsEwA==,type:int]
        session:
            COOKIE_SECURE: ENC[AES256_GCM,data:ebWbWA==,iv:h95EQIdVQV+Nca35VQuazrKXaqjPfbOHVXK2ctQIWug=,tag:nfIx1tb5f+3sZ2rHJo+r2g==,type:bool]
            PROVIDER: ENC[AES256_GCM,data:2+dKnFo=,iv:NTl/fZebIc1G4omyZmm9/p3TMPy5fC4Mv3HPmWZ/hp0=,tag:WrrHI5tzb+n820R8DfkdIw==,type:str]
            COOKIE_NAME: ENC[AES256_GCM,data:24mNr5l5lU8411uniGYNoPT/KSvgdw==,iv:7xjZYmfnmv2CVj8QPwVQtK3mOTpJnZwfnUbM+/TrDaE=,tag:VQ6wpj9DFOIqW5yShg1qTA==,type:str]
            DOMAIN: ENC[AES256_GCM,data:438r7TFXcNWmObCsyOwU,iv:vBa9fbM9+P7j4suXSYt8tjYKLgKRgZeLrm7Z1ytqick=,tag:ypY3rpLGfhW0r70HgFAInA==,type:str]
        indexer:
            ISSUE_INDEXER_TYPE: ENC[AES256_GCM,data:SOM=,iv:L3ToqXsvdBYB6NKtt/CYx9bj92jp1um9XLgtP0N+NYg=,tag:7w8f+G+8cOlZqfloReJv4w==,type:str]
            REPO_INDEXER_ENABLED: ENC[AES256_GCM,data:H4CQQg==,iv:tXiSOuATh2jhfgwZE7b0QjUFblZ5Oi3LS8cKFXstSQs=,tag:kcQ8bTUT9OnmwakJXvVj7Q==,type:bool]
        service:
            NO_REPLY_ADDRESS: ENC[AES256_GCM,data:ZQ/eI+EONnOrb7QhWkBlgF0M,iv:LPAPTRstjlNZVUEUKX6JpxlIRPCs2ZwVVzt+kt/26zM=,tag:ZlnM3N6n9OU4zj6rfAPc1Q==,type:str]
            DISABLE_REGISTRATION: ENC[AES256_GCM,data:+NJSBQ==,iv:nBW99dCzGtqs3AuVzGZ7cjfM35npZDdzZ0G6oJWrd1M=,tag:ABSZW4yALQpybdii5/z1TQ==,type:bool]
        repository:
            ENABLE_PUSH_CREATE_USER: ENC[AES256_GCM,data:qSRSNg==,iv:pKsZpl/hK4b0Bj3QlYdwQU1jGSkPQBO2lixqfl9N/Cs=,tag:31+khxa2s9Q90Zk6sE5ehg==,type:bool]
sops:
    lastmodified: "2026-01-25T17:50:22Z"
    mac: ENC[AES256_GCM,data:P74tQC9xK/Zuw8Hbsxze6IFc/o3fqTGIZlTgfWDLfcCyNiv2s6Vwo3upcKk67roSjZ7U0XmkDR/5sJYkE/0xcd5NU3Sj+fCVEq5yzcFvDShq7gVAXQB2TFb4/GFAqxvXDju01s/MdkQw7c424uY+m58LA/e7KPhIzlXQUcAJfIk=,iv:M0FEFVmpQKAlch9puvP9hENPw+Lf2xCqLuHuKNhehrU=,tag:QlKezbDMNFpe+ZFh3ikXdw==,type:str]
    pgp:
        - created_at: "2025-12-12T07:29:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ/+OkuAgO1oo7A6IU8xlTAQK9UBi0Ot9u+i1ElXkIfrU4H1
            tlEX4pQmMZSORGDDaOPEJeVgp5FPvhaCxz5hJw8nL8OZzvemqNSo66+9oVOhcyvl
            Ttu37VSHqR5vV+IizGtILJTHHmjBxy1bOU25kN0UV+wtyvFxGnwzUdff9pJvlA23
            ESgkkicELCrcZNsL043q0NoYqHlrbYpObbH3AIIc7wt61nnVtpRBH27y4rNt7Dmf
            VyhRw5fcgYfjewTQ/D8RSBGZsO6+2c36064IIIOXyQPr7ZnDB923Iod+/UFGMM17
            Vw5J+xGC9A1Dq5Iq1gs2cjLYjAdhCY1LsJdAsF31iZe9h0rkKmiAWQ4rKnFYRQp1
            /OjNwPJyoJms8ra3ZeIgcnVuP3FnaoNaXLnfoYGibconYmogWkKDXTsYmvd6Rk6+
            xJDrZvzmRee+NFgaQyxGLu8FjPw5B8DPYz2nv/CB1Oxo6LOY5CgJ/jBHs/3sSS8E
            M+I0RcL3ueHEohUlap4jzap6PZoY68qiGGu8pbsTCAs43xHVYZUkACUdnPkYVApl
            nXzG2x7ge3AAMQhRErz1SWlGJQy57mlAhIjHL6CeOsOvaVUgULlit5mxA5BhRK2q
            yfGSlCOQcARY64SSDwws2EmfKIyrrPC6irq0TEJSqkoOXrjSTN2idZThIZEmGj/S
            XgHu4pD0ZRF6Ljz9Rlh7iFBZ/eRa4q0OVVT1ABT78apoAk515LRbSzhxtocuBkzt
            o4Bp8UIZtocuHv7XsmMEsIluxLuIHoKDeG4SzoYcDbTN4RqwDd5CAEvHyoJhkBM=
            =KzHT
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
