image:
    repository: ENC[AES256_GCM,data:sItVETWobYVrcDyAdX1iF8Q=,iv:ckb4Er/rFlCrCXYMhdh79Kwx7EYdK83IMVzKzJ7K+B8=,tag:KVzkZaMhReThJ1+AxwFx7g==,type:str]
    pullPolicy: ENC[AES256_GCM,data:s5oQrLH5uy1uscIt,iv:AkIRjq9t7KJNuguCWC2ESrJB3I+r0YmkJdqhI0Vp6jE=,tag:vP4f3zMMTpJf+wA9MAxRkw==,type:str]
    tag: ENC[AES256_GCM,data:bLrx8BCa0g==,iv:oTPUcNNlSamSn1dJUzysDOdelsZYA3EEGzhUd/tIHLk=,tag:coZaGL0oQ+9DRddsU4Mn6Q==,type:str]
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
kanboard:
    debug: ENC[AES256_GCM,data:aUymYVc=,iv:9UeZVTarRlqotDub4rBJ4o//Evlc2Gyd1warGa0xDMA=,tag:rTr4UlXMvN4rDJuQYPJ31w==,type:bool]
    databaseUrl: ENC[AES256_GCM,data:2hBs/NCbZC/UlWMcF/UcwbSycKaPshsMrujnDygHWvlC/tY1OyljsUMD3kk7zdOlFeOW2EeTMa6Tvd8WA0nQF+DLXK4mZWrDYOZKAI4VrUITlVqFfcG0sGU0JtvuJMRylw==,iv:3TIjNb2hodLHywM1D1VzTyK18hNxJo9vnKGQZwm9w8o=,tag:5wtvdxzHT54urf2Bco1AUg==,type:str]
    #ENC[AES256_GCM,data:vanWDNviduUmKY0DTpaymLV5ve1YuvcIAeGoNq2RK8FfSOI1Og==,iv:Ek9OpzF3K5WWceLF0Q0DWGSvSewJo2l/Pj38Q4venzM=,tag:QtPHgLbeuMw9FiMTuikgRQ==,type:comment]
    plugin_installer: ENC[AES256_GCM,data:HwD3Pw==,iv:AXSTP+YWZH6diME8kZOOAD5CVtwM9KQFrKZTvR60WfU=,tag:FmdkyMn8HSu06uSSCpzSkg==,type:bool]
    #ENC[AES256_GCM,data:Hf2j/5RlbAGdbXIicmPnfPvgcRPSSZtV+ZLW4UN6vljhfIEk+9mRskQwKQrpe3NrgZDMZQxD6XwafbIMvQ==,iv:XxE/yBgfXVw8SFF9hWhbh2bwclAJ7aNaI9FvGZVSXEw=,tag:UI8ww2GJeNqhRineayC2Kg==,type:comment]
    #ENC[AES256_GCM,data:phgSvaUkSjWmBOO0L6M7wGyL9z5EURpyk+x3ZvU=,iv:wlFnLu2m1pIcOlAYuK1OwBbwA1TvYZID/dREWWoE0fg=,tag:kufrZAFIkyCEFAya9xT4QA==,type:comment]
persistence:
    enabled: ENC[AES256_GCM,data:gx5Bbw==,iv:61E5rTYzm5ZOvx5z1JmHNbvlx0zj9X5fSpkrInSgjrI=,tag:1L27mHMRxdd1AUHl99dJfA==,type:bool]
    size: ENC[AES256_GCM,data:b3A=,iv:9R49Dru3iyf7HTFTKp6I7G7IGaZ3QK7kp9BchK+wpI0=,tag:RFFkkQp7zcIIm8kPsJ8iTA==,type:str]
    accessMode: ENC[AES256_GCM,data:uOE6BS+YjzgoTa1p0Q==,iv:fguBoi0ri5TXOPmtQSaeJdOSjuCns3W+hR5/QH3Mn5s=,tag:KSyuKaROvTw6fPmCrzb1rQ==,type:str]
    storageClass: ENC[AES256_GCM,data:XLSMUWsa2zc=,iv:WrPPVS8O1IVZ8VaxaKq3MkDh6RfGmh+2G9CnvgWQ03s=,tag:76XLWiL4VtLPwOOHUdWYPA==,type:str]
    annotations:
        helm.sh/resource-policy: ENC[AES256_GCM,data:UNEmXw==,iv:43WBKx9OHURKyyRNzH3Qg/m07fpfjablSpnpdaRS+N8=,tag:3oZgsBUnKN31HuLFlRg2Uw==,type:str]
service:
    type: ENC[AES256_GCM,data:yMFoToK4z8kf,iv:0FjEaQF+a1heY9wRTj+Hwpyuys6SyLfwafTd7UbloXE=,tag:X6GUSjVkCFGGONBaO8Oteg==,type:str]
    port: ENC[AES256_GCM,data:cu8=,iv:Uu+CLzy6D4FbtD62dkxphinM9SRZ4Zdyuyz+TC43Ocg=,tag:ox6fftIV4HzLokdh8H5IVw==,type:int]
ingress:
    enabled: ENC[AES256_GCM,data:bvY93Q==,iv:EqWBHyBKAxhyut9k5sgN3rGOQeBi23JxSMAR+um/8Ts=,tag:tcbaSgMfKElBVoU/YZvD3Q==,type:bool]
    classname: ENC[AES256_GCM,data:m+eWILA=,iv:RruesTvLumlpuPo+4AWBGG5/MrGKbAYgH9jjEZx8tIQ=,tag:8OfeZDuaf9EqiB4Ds+KGtg==,type:str]
    hosts:
        - name: ENC[AES256_GCM,data:g5VaabEef6KuyIkUOwZLUGT+,iv:UhfLu8gErHhIOlAIi+hkDcCDPlRN+LSqvfcIe5furvg=,tag:4JF2PKoIBPYZXA03tRMt/w==,type:str]
          tls: ENC[AES256_GCM,data:/U522Q==,iv:/SGrO6Zuemd4W8dULGX0rZYrV5fFXHa2mTcnJQn8RJI=,tag:PDRu1HuRXPtH1EKKICu0Jg==,type:bool]
          tlsSecret: ENC[AES256_GCM,data:lXCbUYhp6XR5IzmVSaYbehEBvU0/mA==,iv:drv3PMCAsdPR8FoLwM28qC2USoNMx5aw6n9qfPmae74=,tag:Mc+MmrT76WZmvCEKhvakhg==,type:str]
          annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:IBWwzxk9+GuScYlCF+Xj/Q==,iv:LlJCYwqPXQdchm+3lQ5kwQaDldTMI8suqmjzIKfRkf4=,tag:tOdjj+3eormVV0nrUCo8xA==,type:str]
            nginx.ingress.kubernetes.io/ssl-redirect: ENC[AES256_GCM,data:GYDEpw==,iv:WhP3WdqeRdQzapt1nXXS7jeXG8RnzDcQEYrDylnyZ6M=,tag:zrR/nzFQ95UsWMUJ2kzOVA==,type:str]
            #ENC[AES256_GCM,data:4HvNjYCP6eJ+l+wcgN8KFh69NeLwOxtriDAwHo4YZNqKTlgq8hzw83Ltpj4n0VVtForBj1dsyOLSN84R8Oo=,iv:t0/w8ktzZap3UfDbtHTz11+rpI7sIZhlxRkygg7Zs/8=,tag:ZJCoyqVdsgU2EBNQv9b0bw==,type:comment]
            #ENC[AES256_GCM,data:K64JtPsENhMzeFKlPLz69Q==,iv:Cz7Kk7jD5tsk1MlhyvilOJtflTPpVAw4k+Oe7/KpSfQ=,tag:CNvXkh0Mdt50w1qRpBtScQ==,type:comment]
serviceAccount:
    create: ENC[AES256_GCM,data:gUve+A==,iv:5QZFnydoRG2Cx3wEaxQrB/13KFmf1J7rSqqPhkiQiBM=,tag:ze0pL1zrcqKdINLwhyIx7w==,type:bool]
    annotations: {}
    name: ENC[AES256_GCM,data:Nu3A98Sd2RW/fS0=,iv:jbHLRFbeJKJYbHYjNa5GPZda0A9Ybe/OgbRNk2olmG0=,tag:QxE+aumLXegn8e7hVyGKJg==,type:str]
additionalSpec: {}
podAnnotations: {}
deploymentAnnotations: {}
podSecurityContext:
    fsGroup: ENC[AES256_GCM,data:LVNRng==,iv:fCs6GWvXtxTD/D4WQ1j9/MaCagnDFlhE4pk0YPq7O6Q=,tag:8038Pwy7Cz0UlGWwRZL5iQ==,type:int]
securityContext: {}
#ENC[AES256_GCM,data:iBXsyGRZnH00VEmtoeaO,iv:ZHvzQeLH0Q4U18K3EiVLB/3dH1s7lIppd9eaZDZyVhg=,tag:gn8MdHXlwB958YqkX6FkRA==,type:comment]
#ENC[AES256_GCM,data:ubG4tSy4ikAN,iv:CN2CqvU8ucFZWOEOD3+h6+wIcAbr+00dkAc9KdtIDCM=,tag:7F0DFR73ceaVCwYlxNP29g==,type:comment]
#ENC[AES256_GCM,data:sNMrYIs1b7mD,iv:46mYb6TbrlEy+Nua9B7e8qU8932scAXjdXklCBGNs5g=,tag:o61lwO1GVn7jCqU5OxOOXg==,type:comment]
#ENC[AES256_GCM,data:z/5JwawzS0fPUJdQIVId1v/8RxV09Yx5M67xkALI,iv:9VjRImWmlbuHF0jVICxHbn87lHMc5LZ0ppDGK9W1JTE=,tag:pTs33aiFNQEd4tz1K9dkqg==,type:comment]
#ENC[AES256_GCM,data:i00mw5mfQyWD5Kzh6B+5RaH79dAu,iv:gmuWkpFWC7C+4y+m5kOWc2As7p4/XmE37iTVkFkKAso=,tag:9cJUbnA3hwbdE9AX4kPFKg==,type:comment]
#ENC[AES256_GCM,data:wUvr9i+4MEev+vnQ11K2M4o=,iv:A7hzU+Jmvzy8MnGQjb0yntmNYxeCL3hErM2YWSK3Rkg=,tag:szbdGFl5hsE//Hgl9jcEXA==,type:comment]
resources:
    limits:
        cpu: ENC[AES256_GCM,data:fkPCMQ==,iv:kR3jaITHGbmpOcmkrzazlgFUX8YsXDfJX/DjZ60AW1Q=,tag:2Ffz5Cxhg9yI7hE4KqlORA==,type:str]
        memory: ENC[AES256_GCM,data:kvijojM=,iv:28BHFVt3qZ10eFKmXKk+/OrPeVPB8Pq2uFd4qSTYvyI=,tag://PpfCgSQL/A/wLolfFegA==,type:str]
    requests:
        cpu: ENC[AES256_GCM,data:L+lXjw==,iv:4roOtOd2side2IB3MHTmvn5olIxKGbm/2VboJP6/I54=,tag:z0ekVNzIRQqvGD+h5riCOA==,type:str]
        memory: ENC[AES256_GCM,data:bGT3wA==,iv:e2mxcX47R2lbd29dkE9SwDuouXO0urXeF+/+O7Ujqs8=,tag:QvKJS0g8485ME6kkozTTFg==,type:str]
nodeSelector: {}
tolerations: []
affinity: {}
hpa:
    enabled: ENC[AES256_GCM,data:wGuLYBY=,iv:dRagknBhENgwMvm5LdPJDvJSliSajK9SBl//2ouGRbI=,tag:1jdOcU4wyQVin/j4qYZX6A==,type:bool]
    limit: ENC[AES256_GCM,data:HQ==,iv:W57WNIA9UU+evQeSf7MyNj4kCS50wEhGzwUzP5FZ0Ac=,tag:8AdQ4/yyTLUOHdcU1P2QBg==,type:int]
podDisruptionBudget: {}
sops:
    lastmodified: "2025-11-30T20:27:42Z"
    mac: ENC[AES256_GCM,data:0bL7k8Zz98uJ3ycQ96aznopIJIGaFK8dziCY3em8F9Oe3cbRRdCfGKOiGgrVnWbhV2mBePMkeb38Bq1QmiK2NVwC5udDhLHPzIJlY+cDBJFkHIAcPnkLQOahxcEuJlDHGfAlc/8VHcKlHvGyCaqO+GshsEj7x5TivvsIyuUpT5g=,iv:K2zTLmjmzIi9USFEM9GEoSjq5oIc5XfYGB0NYV4nD4w=,tag:E/cfU88tW0yIkcXcGeNyTA==,type:str]
    pgp:
        - created_at: "2021-04-27T09:32:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ//TkfI8fBkB7AYyZOYXWknCpHyg2gFgnL7ZvlyhAzRsbq6
            4EBa4EbCVIwxBoNPJ7YGg3GxhIiXMcyxtUGk6hK77ZEUB7G2IjZAz7OfsVcuYrK1
            MGcrSuqBzbIIKclamhUNhK8RVcqw3qSNAFOm2mJFnpDpjNjCT34cOY4pOUGzAHwO
            F1wMH3dPI0O7ogY7PxknTlbwWx2FaK1vzg9RGhiF6SI2t6gOK1IoBPiESCQcVbTM
            kE+88BGm/+LQ/AJ/z8ZaUnI+DVAeZKlev0sysUZmpiUBB6e3XcO0cNAzXlbWaCvV
            4gzwdsbqcSvznRAoMm2wrfTYKDksAeTf04sr9odnpscPCT7errh/MBTErlQloKua
            VBHMyhzT3Km5yMeGhkt+wZkswqGWGKlhUFUFKdlMLTlsIJ6I7A5t9fYZQc7sReUH
            OoIXifos294lethiy0oF+uitYII6b0RfUC5Kd9i1JzkdTcQfFLH+orPcoOrvVtu1
            kHFRphGbtISv4fiI0HnUZyWWzRsP9+rE6AG55ENzlabXobqehHXZ9dz2Z6y84TAX
            M4ajFJpmODaNCirXhYZHRkTGH1KbKsY+adJyJHmQ6FdopclKxPnwnqFXS5i2fjaz
            wVYM7ItocoGANkgeAqib2B+lETtUG5d9+CXz2rgDU0G0+IkOPErHE5o59Kjtp2HS
            XgEJvc7V5FEADozhKf3RLUBPKj2Yme3z7NczoMEke7aOpBYSPwh9VEBSazoA3/3B
            o3NuuCWMxypre9SBM/0h4w9p0QoIAUrAWb1H9KxTNOjERq9uyzi4HOdwRWTDF0Q=
            =PPcr
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
