kanboard:
    debug: ENC[AES256_GCM,data:7YXlk20=,iv:MgsZNfYYxIarwHF23TfZWXmp8HoRwtF8/nAWta/3QhE=,tag:T3mCNa3RrjicAxaMus+bkA==,type:bool]
    databaseUrl: ENC[AES256_GCM,data:t1ArvUMwIzHUpkR6nPJt8P6cT1Y1H8ahYlwKyIi6IvBqq6xawxtKpZ9QWqOpl6N2tUY6Niiu84Arw4yEXFocqXOnMiK/S9e0EkJN5q3lXe5WF1zBk5FlLs72tYME5IFrPA==,iv:GDyyVXMwYx0LvNBym7gU9VrfUpz9eCBQKqf16osWIZQ=,tag:sz+80wvMi0m5K6ZueNP7iA==,type:str]
    #ENC[AES256_GCM,data:luGuTBVdpa/wlU0MrIpGHkEEEz6ZLW8ZTrwup8AfJBwPtaaDlA==,iv:I38WCIe2idB4cwlNH1+jbvZXjttnoSHCxiuIkq7Rhv4=,tag:SUqLzy6OisF/yT1/GRNvGw==,type:comment]
    plugin_installer: ENC[AES256_GCM,data:DeuFTQ==,iv:3oz7XPO7vw4r9WbB4Gj+68JF9TzngpjQboJNYLJfGGs=,tag:WK9msYgEEjM7ocK1fKj3+g==,type:bool]
    #ENC[AES256_GCM,data:GvRlFhEIFIMIGyFhxeze9pdDNgtOLJRv9mOmWNtZpvIs2fGBtqat7lItMYFCVbWLFawevm9j1pZYFtuYdg==,iv:bYk73LsesYWB+pwfD2ny1prp8G+q0Djat+7tlPvzp/A=,tag:3WHSOHF3/PhcS2KlWyieUw==,type:comment]
    #ENC[AES256_GCM,data:PRbs4e6EERO9YUc9QYHbPq5bn4VW7iLdHYBRPuw=,iv:HUI4oscSKrYRp1D38wh3j21vQGrxMKNXUjvPTXysuX4=,tag:/kz+yeXxUBmiMecHs3lF1g==,type:comment]
sops:
    lastmodified: "2026-01-25T18:11:59Z"
    mac: ENC[AES256_GCM,data:CfwS9Nm7j8t83K4XtCfQNb+Iv4YgETTLNDXo9Rns5jB3CJLbuYERTa7Zwdl/SsV+GBKoa6S1OZ3cvZaUlOJKM/AUke/HsS4GD0JEmGZPAv7QdOJXcJylzfvtxif/W4Rtl689OriYsGL3esNaNKuQqFBjXZr1lsCKdmVaS8qiO6A=,iv:/rmEYfnrn/TR0TVN2D5OQkEuD7Vidv4KbR2vf0Zq+Gc=,tag:DshNHt09yZ/cC7Y/1lrqFQ==,type:str]
    pgp:
        - created_at: "2026-01-25T18:11:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LARAA2CErMpA8wPq4WwUWCpLaLBTayi2kOFnohrKQEkzMqFQi
            udXcQFI45ngIj0+yZWNvNmL+W3pZ8j1ageWBw5VFx/CIwaPy0LndVtxlKJtlMVfv
            pJ/fdRLR6nW8b80EewKRNxxz387f9lnJgaMd0XCPCzgm7HY4Hx7TL48APdRow1WQ
            BYn59WePyhnLYdZMndfVRF8pT/u/dSURh4Y2hGiirT4ARTAHGqeBeuNzcODB8Ewp
            B155bRCdrFz+z/lFT8dkORCKn1fhFe6TNiHtkG4CE9LJ4ZKt0IlOllE3EZjSdUl5
            YZdu1m4+vX4CGoTfnqLQCNZNYEZnPfXTpfzhiiA0dsZsvyrQKUPkN6eLBYBe6QK1
            WJpS/ZM+uXU4GL2cKkWEm/Cx0eFdoa2PJ6o3mXPNLm6hRlXu3Tk+IsDQ6f27L7Mu
            4W5L4PyHL5b+8dxYwWKak/Jf6/BRIWCxdgWmjx+N3jQcvZV2DX1GLPl9kEpK/rw1
            nptntJk6fpVV+S4sAsMeGUeE8mVV1S8NgCbdQCTYaITR0k99fUHjGhAuSicBheOW
            fjaRhOvbo1busrDu5rZDZk4Cxtp5k5K6aAi/CmO/QyGGt66pyWEpEYYm+s+PQPhk
            +zTqbR4ciqJiXuxrSLrCZ565Z/M9IqPnvuAn5z984SBeHbUkAKuG1TR1lB+wX9fS
            XAE/gdPIOL2wNpXQCi0mNnuSOXzROrRSg/jCzr97F1Zjw4P8p2UI8/+60rV4iLvt
            UM607dwSXqKrEVXL87zZjeDSsfbUK8V4FsbU8s9m+ZEKcCN2Xjhx822+skd0
            =LVLG
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
