ow:
    apiKey: ENC[AES256_GCM,data:7KIc43Yjjlg/PYa1BrI/xiS4OqJRNahPtWZ0a7rVLk0=,iv:QvW2Mf/Vj8V93qWhKf5ryn8pUTtt0/rP+DtX6EX34AI=,tag:9bNE4+hQtRKquIEFi28M4w==,type:str]
    city: ENC[AES256_GCM,data:fgRmc7C52wnVzw==,iv:XZtDnU3HVCDeHrJn4d1fVHk5K84IqZ0Gr4skB6n3qGU=,tag:xEkuHh8WkOIrKoSBRbcUyg==,type:str]
sops:
    lastmodified: "2026-01-28T08:43:48Z"
    mac: ENC[AES256_GCM,data:TedUrS4H5fxz3TqbXg2Vi2zNTytLHVLM514g2ZUPUcW6UmUdiYQ8wSzJRgeubMI/ewzUTlHFH0tl76h7W1bP7f+k89eKjEFyKE/GxJsBLE5IGImk4bFR/O/VSvtCYSjCpRzywlhkzIBoFglcxs1CBWVURoVqqKK2mb09ZsxUHeg=,iv:5Axnk0kp+uxAmcgWL5v26OHN9xLt38/AlttlvjMYwGo=,tag:TUHRrwshDjDHk98/HPgmuw==,type:str]
    pgp:
        - created_at: "2024-10-24T12:57:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ/+IDl6CFmw+v5Ju7BiTukRXcfvCbrDHFOoAgoZXf6akcP8
            ZfJuAQRdSI73XU8iBwazJ76eeoiELVGxwDsauZi1kLfKXWifRpsVMD2k9YwWeqyS
            W/wMlGxrzd4+7wLbKZlEkhU4wqoMjIRCw1GCaOv5/Vii/w3T8BDGmtQzjlvHLiTs
            M6AkW9QddmuPnKgjP/ezpcZ18W5TlZzdLJ3G1hZUC74kwKZJ1XyJ+CSnW1ktHBqs
            ov1BBzN1e7iAVekCqTENmNRSwO970hWsu6XqtZ05xO9zvmVtjIB2JeOL34CBu33D
            +3x4zeAoEgU9zahTcrqq224Smw3n6FsKI7BqAM7mHy4xYQMsaU6V9/IhMisS91b1
            NPfeSosCsi43JinMBU5vrjT4Cn3jQDlhJGq3RuEz9o92BDfOKbYxoav9hHVYNa8f
            1js8nwKghxoWuESGwtM1zpwvGMmwN52HoBsRXb57C8bnkZLTV+6IThHt9ut+bFLm
            1OAykpDoVf+hcGM+E/Vxw63Nhz07my2Dz2fqGDaCIOjPxjqUSuNxSAmVnIfdV1y3
            1tyifEh8IvcjnP+e2A4JkIIbUMkWnXajxzxKFMEoNzh/g0/s0DxJBZgwK+Qczgno
            NO0nCukYSOI2LeuaFDzcP1HjfquGiLcpbvB/M2cyG4Quf1ZKfPN8CaKXTf8QvVfS
            XAGpK0is/xVyhdQrdq51AJp+2NZFwyM3+m4w8gJwTMbyr9399mi9GRqj8lYKaV7N
            WaUDgb6wFX3lR1scRQ9jp5frURdhuenfu/thjc6+C3YwbJ/Wd/PrhYoEGZoE
            =lopE
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
