#ENC[AES256_GCM,data:8o1YEUHlvchd594hheGkB2ItF/KmX0rAP4muzg==,iv:lCAvMUleuX72QFLSAgwRmE8uevHTtYlND80FjrU6rvc=,tag:ip/xRiPx7qadMe4AjHrBCA==,type:comment]
auth:
    enablePostgresUser: ENC[AES256_GCM,data:xVM0CQ==,iv:vq/124AkN6bjxm0Cb8u1Awf0ck4rvQm21tbGhMfPzXc=,tag:jSl3Hh9LHnFhEwbXoibbIg==,type:bool]
    postgresPassword: ENC[AES256_GCM,data:hKt5WKNsNOCp0h2sSoGIZwvW//Wc6evEJx0QrzllRV8=,iv:ym+Kp3glzlL0mE3kdlZeMwAd7dXkP+XMaZGXKiujCJM=,tag:fjPgQ1mayklZCqShxWzn6g==,type:str]
    username: ""
    password: ENC[AES256_GCM,data:MGskzXlfFAgrqUd7QJpuQIJSB9wti7fK+b7Er1mHJ4c=,iv:bjvBZpMsG4ojmvJHjPWN5jFAxqlt2QYzBb3yselaM6s=,tag:dHM/z6CsdDIoJc1xIeqlTg==,type:str]
    database: ENC[AES256_GCM,data:oN28lRR+cLM=,iv:zwRlsDSwacQnR9+r6KSVn4oe0ScCOgxfwFQ7TOPV36I=,tag:YPDrE7w6d/0mcR6w9Aadjw==,type:str]
    replicationUsername: ENC[AES256_GCM,data:GrWrk1xUUQFV2JA=,iv:3YRW6oGTcfdcZmNfERfSsms+KbG+QOmpdLzhLqNn0CA=,tag:Nwr6A0K4oLou2+3QXNtylw==,type:str]
    replicationPassword: ENC[AES256_GCM,data:Slu+2D2u9bEsqCUpgM3vdvxd0Jvkm00YPYkPpWYpPbg=,iv:0A08/zG0o4nuHfMtz2nOBI074ogPT9Hq34B7+x0xY08=,tag:gUIgZ4bM6hNZLy75/7s4iA==,type:str]
tls:
    enabled: ENC[AES256_GCM,data:Sg2th5E=,iv:oJe0eDZXrT8ZxeFQc90fyv96CsnPASN1gsGomMcZx3A=,tag:unrOL5zl6mz2GcW79FvcpQ==,type:bool]
    autoGenerated: ENC[AES256_GCM,data:g8bu+Q==,iv:tk03Bi6ucZc+msnuhxohzl1i66psO3Z/Y21AnKHxp/0=,tag:25/QKCrurzZJm3O5y75jQg==,type:bool]
    preferServerCiphers: ENC[AES256_GCM,data:yrGAJg==,iv:iEtB5RZz6CF6zqCE3rJVqcVrsoSGTlxsklLwE6N6AMs=,tag:l8WhkTRkl8t5Q//Em4Oycw==,type:bool]
    certificatesSecret: ""
    certFilename: ""
    certKeyFilename: ""
    certCAFilename: ""
    crlFilename: ""
primary:
    name: ENC[AES256_GCM,data:vGLovP6z1A==,iv:/xuCtbS0sMwgTNREKe4K6lHSljDv2KVV2vbhA1UvzE0=,tag:ClFRarHwUiA7WIS6ui1Zag==,type:str]
    configuration: ENC[AES256_GCM,data:z2sJxSIfn5rXpfHh6usjbDaDNDvbiWohZtiPRrWWhre06kuiEBC5qkeyLxw3Pyav8guOdv0lILTKZthARjojGNUhs1wo6irH/bL9iBTJSCV3v56eemFtaQrBGv6bILc05ISo/CNxueOcNA4f5H2XvienW+JVdwPqoPVnEbBVN02AFKCWwF+X4A83KMfE60+r/lMtGDoKxuczITcrro+/TL/sz5rNrRfdRJSy8fxKeA6NaSfFVWtOgnN+5oOfqUBaCRR9s4JRn4PsgFjf9jXMVLIqM2mimMA7nLbq35+28OmnCPJxrWY3ukcb4e6rUZ3WRQYxC8ruOgQBl6GWY8qSg9yoKkFJBVL0rp+C+lBj3L+SJtB5bYgslI57BqzaZ8QAUOSZ/ah9RxqZlrKJ18nfcgvTTg7X9oz0iia09nzunwpRAyaQZAqeWPW6dTt+GP1l/9XOUfCOMKCSmsMfOZUl+xY5UCMUXXR8vCCjmsTqdHatNSq0OoplL0dKa8x7KQP2rUoQY3T6Er5MmGWsDv6FrU1MtXubSgCygKsRjK5hW2l4x3G3rVWTOYxTI1Y7q41F3kUdCkQPSlaN66YWFri4qgTRT2VOq/cBHt7jAmJ++sttJZPhjmIs9qpqHdl7fmow2FyYvEaC2BkStMgydZiFxBa9gj7nRCCzPd6qdSVBnx89zK1TncIk4Eiohk7X3SyMvGT9Gj6fo7bcZanGycznyQpzkNeWg3uYpWz3cvB1oYalPgh1pDre4fzocbJ+ytrVLNiblrSlnLhIb24kX27M1gtgGIrsKS3BnGmLFkVWaoBuslpOUEm8fX5B9tXTgK0QAoOIY+lrB4hFsGnTY4aHtU1q5jzCUlMVmnqgl4ZnF1B4sRQ7PspBLwnSRPfhChRgMCDApZBJ2vOwi8zi9l2rMxfYNYQ/TaTOqpSOV9iI4885R8Ge3hqaCWhR4TxpdFOTyzB4wGeYjOvYCtfg5NgA47iE6SBHUcbYtUoL3kMokO4uzNcamF6hZL8u2yIR+ahOXgYxx0OGd2QIvBFJUPBqn4/K/c+nAMevfbFyQ/5nTycjddWVoigMKpx9dEyRxAyNemk3ezSIrLaBCQLWNXFjeZStc/ykGKwdVq7WAHRouRqpgAg7bOSIFN7zsa300QBwcRBmKei5vgYt9XcGZ0clqe9PzTF/cHVcZun2L0bGsLVUtMbGg5btWoFigBHRPwSL5OhIuPSB3YCxPXgmUg4c0uD91YiIDzM2omzDwwSkFx+B9oOYR35mWcbEcvhs8pxkL5uPzXDpMO7kD5aFqeaOMwlfSi+uOgp+vb70vyVUUoXJpzqwKUl8/xwv/+kU,iv:+ytCF1OfmvlWckqjamTp6MdLVijRKL9HmTBe8zdx+oA=,tag:SCmNMLOBQvUB0nZ+2JtdEg==,type:str]
    pgHbaConfiguration: ENC[AES256_GCM,data:bHuvQNI48xbPnGQjgQ9V7ACbYECHi2qhQ7GwCjbKWBDqXQNEkOYl9WvurAIhN9K/xiaRPVebcJpdA2fnBBNoo41w86HRNvWLo3H8SqLuvVxFr5/nG43B,iv:oDe5K1wPHYmLVChQBP/N70B+bzUNGB7kreJuAMEXxg4=,tag:wyvR7rntSu+MOb1ijrfOYA==,type:str]
    podSecurityContext:
        enabled: ENC[AES256_GCM,data:NiNoIQ==,iv:QBlNzfC3arXdmMB4jAFK8/bDxRck8zlbquEKFKY1TsI=,tag:i6bx7z4rKB8qFTocSEVDAA==,type:bool]
        fsGroup: ENC[AES256_GCM,data:nN0lgA==,iv:nCYpnak18HR3n3EFYeHZpk3CJeNFNMkcf+hW/57mcec=,tag:24AxQQ378j1L7ElZbHlESw==,type:int]
    containerSecurityContext:
        enabled: ENC[AES256_GCM,data:fHubtA==,iv:QvcK64vdFdA+luJ5+/t/KJ+i2j0v5n/O1/7AJUYFsW4=,tag:b00uhzMaVswTyiNew6bLAQ==,type:bool]
        runAsUser: ENC[AES256_GCM,data:WwQ2wA==,iv:oefqhI6ThF5VjXbl5KJrw2DyeZPMoKj7R7uG5rUU81A=,tag:0a5XZTTmUqhWEkN57OAoUw==,type:int]
sops:
    lastmodified: "2026-01-25T09:58:12Z"
    mac: ENC[AES256_GCM,data:EGspsPZ475a7laCvWBAl2EktXBEFoNoDNabHJR2bbOsqf4myZ/NGz1iFdGpttBfQODakgu6b65jWf4t1/4AVPp56yIp/ixKwEiKnkYRtRhXwoZjZHaILOOqmGzvQBkLsg60hH7oVoLqAZ3HVrnf2pWTu7CDYkohsY0ySaldwvjM=,iv:u9sd215o/07i22GeHj/qLeaELU3HQmJx4BI+mWQZcGA=,tag:zPM+ckNnfKuhjHnnqF9njA==,type:str]
    pgp:
        - created_at: "2022-11-05T11:19:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4APDMemWJ+LARAAp84iUxp1fmV0qrr8ZvPSEJ/lv4KjIbmCA4WOllX9sEr3
            +OxlanNIj1fPXi7c+ROGANiJH74ODQdFAcJQIyO8nxiLwskPJUdtvj2tga17NyYW
            c3rD+5J7r+/GCpqhkNtOLrbU5LoFJsNGd/KnwO46rUhfCaMvQ4QMHaPm639DmKtp
            w5J8yDNYquJvmDDJzXGyxNGRZrTbVSnY/bu6BxRAl5D5DnVzYnRMNtTsMviTS425
            lI2QtqaD7nTfGJluOSkiwCwmlQZmqvbIevqnnVBJ713CWuAtZIVumQhd4qVqjRuF
            mc9TY3OPuBI8pB7ueV2kvLbqjaQEX8W2C6XZjvjHvMXA16nde3h/c25W9kN3MHuN
            PnWMjYjTbkrQ1xkm02UPiVxiB+4bs1qxt4i9YcGE0FgL83ihahbLNlKzRWSRH/Pz
            MmnAMnANvD1tIEGKuBehisKbCIithGQ+xt0Nf2DGs8J6EO/4isBFk3S43vNce+uG
            o0HDZITVtE32Im5EPsvoTuUYBzHdMR9LKQ79NtR/DUT7NEW1d48MkbUgb6nPI/bS
            u9Ez4vSabvgqqINUFvGNAFLti5nd3ZTrX4ewtb80j5z08RQoveP2veTFZNspfoqY
            KvwiUBLE8TElPqNFU33nkl78APj9mWBwumD3ph0xpO54htdW10xyXmfEh3vfBsjS
            UQHoV33O/VGBkQ6jsEKpO4ivsb8QOJDQE/xYJnkXWDJDWPsikRhbJDieZ6BO+xuV
            xCB7G3hqBi+4E5TcKsdYeuCgDY86eGT1nbecJVeinqFf+A==
            =ZmRY
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
