#ENC[AES256_GCM,data:9okiGfvUGiQy3JsE92FS73FpsR7VBPmQw7r/rFCZ1Blbxeup+WAENM0sCtZYLoReiKjHjUJfWaZ4sJHJJpyLOzKYuaogfJoC7kY=,iv:9jB4XPqvDpwpr032Dq/9CvO0gHTCl8+HHlj5hFIvIJ8=,tag:Ruc8t36cGCAEbl6uHqk4ig==,type:comment]
upConfig: ENC[AES256_GCM,data:MKAcr3fdVrCAMvFeDpXgHMs+N+nYXHenyBitmxQ+VBeW8EKkkc7Wc2gfWvLTdyORWf8Zp4VNfL5tVbWkKXyZEQKhAxKxfyOjpsvlLSa6/+5khz7IyVgNKdJs8j+kIqpK/0UrSQyHcIxhmJ/2BIuDS6pK+yaux2r+/CB4uSnPuewZ0B9VW/4MpKrgn1fneijucoPi0tIX2gLv0XNWL5uhi5yIfWC6JACSCZn1ShTo/PdZbw+cK9XooTyLCRRgoPptFKes3iUYxt5Fu9IjK5tXdYSkraM8LX5lOM+wfeDq+1WSTmvBcJrx0m9YZwthaAsZ49grPadWRFpgEPFzVskpKFzTIHUC8wxaz8ve7RBcNcca8CY/SJgh7KMnOxDrweNM8H51HlUyFbW2t5cw7ffUeA3hh+Ptnz1GFZL9dn9/984kd8+dYp1QfTbHFD7fbokAHrzrdneYymbQQ9uzKSrATI3y0BilhJL5b0DcVg09qfXhVxhRZdVhOTajiTZ3y37aPHyerGMjjqfacSfAA84gdlXiEiyVaFc+8nazypiECwRnBhCJgbRiFD331TiWb6ufWulQS54Nk1zc3qLkUbNfDNIrQ38pOk6qVx0+bhWLsfUW0ucQjSaODrbAlzX0MSL6Eu310hOw7DVbejnko16F545l7NmkqT3GCVuE7hiDZyWWvdHa/AJqeAAq6jh6aYOls0T5kFdkoFbXRddrTfBxwSBKDlt7kMDQB89wJIq5rZSdS/1nhjxyhc4z6LwJ35dNDECmU4pKkA8VMH6ySSbyL0Rd1Pevj3A=,iv:QNk/csUpMg09SlBEFNwBbLZhd7PxMFjOnDDug0FDDuo=,tag:9zCTfEv2qWfoDAKUs7yHfA==,type:str]
sops:
    lastmodified: "2026-01-25T18:18:01Z"
    mac: ENC[AES256_GCM,data:X8WG+eDe5klKQqV0yz4ZH8GzcXvRFa0CHxKsBUpGnyVi0nmmDCtHnonJsgdwaQYcjY1e1QyUiLJ4+YiDmc3k6UrAIAAAb3jyhG/ag+O1hepWhdzHLobJ6J7uzB0FTFXrccKIox/llxWzE1ZLFU/rNVVtnXUH5qfWiYzo+Dmjj9k=,iv:DPQ7Wp+qRREq2xzxAKySAslcA7Zr+HvlalWkTy3OhYw=,tag:tW2t1WSiHnZFWLDWfhNKZQ==,type:str]
    pgp:
        - created_at: "2025-12-11T15:17:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LARAA7gaHOzOZPe4Ddvk67sGDDWKZAXXP0gfKPbntPs4H48MR
            lYgnRBP/UNYLP5x8VH7/N7KBBtBorILqyb9Frum9jASHRxhlP/OjsZdZtmOB97fA
            oyUD4TGijlw7mEWsu+K5PZrL+al76vrIR9tmITjFxeCWzCM7Rjp7rwJcN/2LzYok
            yWRvbnLgcMvbJ9s5JB3iZpdhRYSEHvMIWrTCBqbwinE/vp49p5N7HLPv/arAZjYz
            NagdnWJ8j47K51Sl9dHROilRHGymQADG9pFgGNtOSeH8xR4ikuVIHpCPhHDnJfEm
            nvIrEzpT7q3nBrWDzIHvG+9/HjDbqxtAP0pdYMRoKZ6g7jJR1ZhHoPbreW7zsY7B
            o1qm34qsVQkMV2WbwMRopL1H/fnKjEO6E/B7o4Lp85eXFNBL0qRil2qZJ5VHx0y0
            wYaHQ7S6OMYE6c7CWO3k4wv8MEqIbBuOoxGWl9J8YCbfQt5TkOi3iFnzeqfLqM5j
            5Jif7QACauRMsmuCbMXRqOT281uNjI/p5lJKik4fTF/DFgRbVleaMYC625j9lGmR
            zH99R0p9vneN5UiMG9GV1nLwShAO2pM0uBUUCENo+VJyy4VQKOzg6TSdrUVk8ilK
            fF43wpeN2MWgMa4p+qJT1TEADRa/nC5GvMd8jKM+ze/0eH84UIb8gRA+StgcEajS
            XgH/4Dxsl1+AsLAfUXCar3EjwPrU/HWO45NtkDzb5o7vrIshedOXXU7Aksn6lmcX
            lgRRY5QNlBrYqLOERGf9ZgrElLTb8bpMsi+dNFI823b1MgpG0hRG+3Q5sRCDgeQ=
            =hOw5
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
