#ENC[AES256_GCM,data:rIfGYmYbl+tnFeilXp8gj5abBH14KFqZE9ETxyY=,iv:zCL8F6lAifAahSZ3Zg/G79m1rkrLMNp4/ATuYKi5WIE=,tag:lEPW2NsldEKg2WUkIuk5Lw==,type:comment]
replicaCount: ENC[AES256_GCM,data:uQ==,iv:itk2m90eoV1iaWBLHZzO0f/ea/cVrZFyXlf0SYCXyLw=,tag:jZCmYyJQnP61o+C+U9EYvg==,type:int]
image:
    repository: ENC[AES256_GCM,data:CbGBiTr3XWF5HrRCeq3WNQjeBsH39Q9qqg==,iv:qVBiSi1iN1U+IHmK2LNJipQadROWqGwNiHCrouq1ZE8=,tag:/peNf8QxhAKas5skSmjLAQ==,type:str]
    pullPolicy: ENC[AES256_GCM,data:XCozz3TjA2eVaKC1,iv:2TxeqUXLqdvJXjfXJN5Be/c3WRXC2oGyUc74NQ3csVs=,tag:M/yxK6ChGlN1+/u+VK7QlA==,type:str]
    #ENC[AES256_GCM,data:Nm81b6Wc0Z7qIqv2AzY4,iv:iZApw1mTQx7T5zy4lbg1y4VrmujH8bxmDHCJ50oGNt4=,tag:Ln3fHicRySGlGBuclhLW6w==,type:comment]
    tag: ENC[AES256_GCM,data:52uEtPBg9A==,iv:PI60RHyQoOkz0dCo94CvliM32DIkAKtKxIocs0/Z9yE=,tag:fpJSDFVzGzYpYjgrROyp2g==,type:str]
imagePullSecrets: []
nameOverride: ENC[AES256_GCM,data:rHdyHH6+1aSPLb8=,iv:XzG/maa5dYA4CbrLOReHa63zeHRZtTY8j0U5ZVrH9HI=,tag:6Iokw4icAixNmwmG8eEQVw==,type:str]
fullnameOverride: ""
serviceAccount:
    create: ENC[AES256_GCM,data:2BCdWg==,iv:qaelpaS8yHT4lXP8JzZX8r7fvX3UW77OgqhCejG2cD4=,tag:Wgl/hOUFC1ekJZcjtspFjg==,type:bool]
    automount: ENC[AES256_GCM,data:51c/HQ==,iv:Mrn3sFls8dPd12dpAOxjKOHlFFYVHt/MjPveaMBLRXw=,tag:lTyYlLitVpggZmm2AUI3og==,type:bool]
    annotations: {}
    name: ""
podAnnotations:
    prometheus.io/path: ENC[AES256_GCM,data:JEWRSyVAzE4=,iv:BNZqQFPQBsF+iqUOeehXtMuHEHOqxDTFwRvB8/CuR0A=,tag:WDbEGR+U+OG9gzr3+8o/mQ==,type:str]
    prometheus.io/scrape: ENC[AES256_GCM,data:eJj6fg==,iv:CmLunRDcExPC4jZftb0NTq/Q7UpLTeMrNgAwhrCWo9s=,tag:yXznaD1ns2P+LM6ZdxCGfw==,type:str]
    prometheus.io/port: ENC[AES256_GCM,data:l/leZA==,iv:aUX389WD8WbE97jJ67ON6nkLRnnjaR/KahesFShf/OM=,tag:gRynGEDAau+3bzcygmegBA==,type:str]
podLabels: {}
podSecurityContext:
    fsGroup: ENC[AES256_GCM,data:Iu42Bg==,iv:YknlkwT2AReWsmelp8Q8TM7RqqGJRiHzGq9sm7xQH0U=,tag:KpIMPqmgt3KYHcuW56jZuQ==,type:int]
securityContext:
    capabilities:
        drop:
            - ENC[AES256_GCM,data:F7WW,iv:5Tk8aFE+iFkbbt1A05U3JR11cvuthnSm2YSniHegwp4=,tag:YjdHx2dhAZkyJQ85avx+AA==,type:str]
    readOnlyRootFilesystem: ENC[AES256_GCM,data:zNIoUA==,iv:D1M650gBlUrG2/dJZ0gVkgbpuWcA3+gA9IeY4I0dBQA=,tag:GOFAy0rLerL0r0rj0bcEZQ==,type:bool]
    runAsNonRoot: ENC[AES256_GCM,data:PDAvOQ==,iv:Vd05YRGH0eRcnWYuOEl0+Fi574N9MyieHWxOSJwoLAI=,tag:eQWc6mlaRqbJYRdXjRN4sA==,type:bool]
    runAsUser: ENC[AES256_GCM,data:3bYW3Q==,iv:6wR/W7aOGObiwOJbJjtZdfsFTANdSpPyydaX7rt7bdM=,tag:6iidFIGDccw/QlTsJJnzew==,type:int]
resources:
    limits:
        cpu: ENC[AES256_GCM,data:GDQ+6w==,iv:GtPF71S+cN5MW6GUPBF33BgHlqlIklD1lFXZ9mf052A=,tag:a9Ysq1/eO0csOe/o1H4qFQ==,type:str]
        memory: ENC[AES256_GCM,data:lWpHqFM=,iv:f/IMgLtBMvsPncO1csRzYWZueJubPYiPJeYFYAneyR8=,tag:ia2QoiCueBL4xcStOVd/gw==,type:str]
    requests:
        cpu: ENC[AES256_GCM,data:92yiwA==,iv:wsS6I/L0Lf0MTbPg0tY9b4fDNbRgDnF7Vo84Cgm1J+c=,tag:PwSlIwjs2DaZCMGKHugPAA==,type:str]
        memory: ENC[AES256_GCM,data:Fknjv0I=,iv:msSoXCwu9oWl0P7s7YpcB03Wt2gS90piQeDNyjwfWXI=,tag:/D/8wl3Y1sts/1JdFbfsFg==,type:str]
livenessProbe:
    httpGet:
        path: ENC[AES256_GCM,data:fA==,iv:Njc6MrQT7WKtRFTmk5gxppE/WZcAQTNI5fSTWUVeJHc=,tag:iT5HtDtlTJ6DbJPEzRBLIg==,type:str]
        port: ENC[AES256_GCM,data:OlXA,iv:XgyRIJEF5BqSUs0ZMPH131jRdKcvVAFOWNwHgRJHGjI=,tag:rB1Qt2q+QvC8Ap/7YDmeKA==,type:str]
readinessProbe:
    httpGet:
        path: ENC[AES256_GCM,data:Kw==,iv:5bRIYlbmQr05XangIMVzbS6BMYSeNJaHlnIqcrsG/rM=,tag:jzFl+zgg+Ti0+FjkDJjPyQ==,type:str]
        port: ENC[AES256_GCM,data:m63u,iv:kbTeG6tdT3gBXiUIdC0cjRdOwUgXK6Yy1rm+pV0dgk0=,tag:5SJdq3CFuSNBmMtBvFfsmQ==,type:str]
nodeSelector:
    kubernetes.io/role: ENC[AES256_GCM,data:O1YVHCdz,iv:MloE8NIBRe/uEmvlnbDog/XeLimAVlSr95zwfcAUoG0=,tag:T3TDeaKQNh0Z+mpuBD7TBg==,type:str]
tolerations: []
affinity: {}
#ENC[AES256_GCM,data:9okiGfvUGiQy3JsE92FS73FpsR7VBPmQw7r/rFCZ1Blbxeup+WAENM0sCtZYLoReiKjHjUJfWaZ4sJHJJpyLOzKYuaogfJoC7kY=,iv:9jB4XPqvDpwpr032Dq/9CvO0gHTCl8+HHlj5hFIvIJ8=,tag:Ruc8t36cGCAEbl6uHqk4ig==,type:comment]
upConfig: ENC[AES256_GCM,data:zF+0MvFBBjRpwRUaKWx4g9tibllmzn2sBYFNiUzdRuviA4ld10bxRDkrub5je5O02ikay1Mobj16Lw4wxPpnEZdDfrH5b5s8zggLTb/wq7A1gI7YPBFhW7uNyy2rbgSC6w1gVbmhJ3CxVoOdHgo95tlVUdersaS41Ci8PpIVzDKm8SixLDTJ12SEy/5pCIwkhkfYkb9+KPxM+gcQUMfYKNSAT59s9ExAy/+qZi5Ukd5vL7wFfvQknbXzK7dBos4WtSIlUQjafp1hCq+Q6yP6CZ2ecdwTmdQbQK+Ow44lCbSR7yMg7xf17IfsQtR4ambFtgUE5aKIAHPFZHTrJ+SGytzlDha+iyy2Tu7GWuGNBvid0RQFNZQgOH/psxlD+pseFQa5rEjp1sBF4wzvlX9vEZeh7Xw4uAQjkm3i93EaKS0j6Nxks+6T6poIFCoD5QLkH+VcAx0c8syeZOhjRaIapL9W7d/l9EhKUzzxxXD9/hb4omIqw2UcuPa3TSe2cJrSfI7VPrPeC04v/2MEXNkEISCUY3nSqAq25sSVnQT5rLbqiyi2/DwomUvKDbSNKAWXtmMnEgXr5EG1prLBqC/fOWdZ8hXpVDQK8MBpO+u+qz+OsUnEuPYEmqbjeRGIEe+WdFOG0EOhyQMNjwCxfaNj/S9xwLgioEwaKCAEn1gjmqa+W8wNsoBzoRrJBh71cXM9T29jmUeHqPiNasoGSIppKkWj+WLA8wcs3BZEhNI1kK6x+/5zucYhYgjv75XyL4HtxxddLDu2JZFCNMeiqx1qQs8EBQPQpwcBNv/Jm2GuSn9C,iv:yZDlFEb3Vk/MG1VzwyfrfU+0N0T62ook0SSlTqcXlto=,tag:vuQwMQUrvuCngJwNlTHrCw==,type:str]
sops:
    lastmodified: "2025-12-11T15:17:31Z"
    mac: ENC[AES256_GCM,data:Bs9aNwdZf3U5/tHhZMVujlTlCjeHQFE4NO4OHD7D/j0VKFvlT8axc30oGaiUxBhr+YWXNlMadbt/G0d+CU/QDQBncQ8/Mk6bsVIq58k645+V9g8o5NGNolLyiPAovLhfsT/dlJ3aLn3jXu3hpsN4JDyUzblqFWMpf7IiOADfvNo=,iv:Fq1Mqb+jK4ul+IEKK/li4T3AEZOzu5W64dx4+jp2KJU=,tag:O0fVbqPA0q0n0dkcZ20CAA==,type:str]
    pgp:
        - created_at: "2025-12-11T15:17:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LARAA7gaHOzOZPe4Ddvk67sGDDWKZAXXP0gfKPbntPs4H48MR
            lYgnRBP/UNYLP5x8VH7/N7KBBtBorILqyb9Frum9jASHRxhlP/OjsZdZtmOB97fA
            oyUD4TGijlw7mEWsu+K5PZrL+al76vrIR9tmITjFxeCWzCM7Rjp7rwJcN/2LzYok
            yWRvbnLgcMvbJ9s5JB3iZpdhRYSEHvMIWrTCBqbwinE/vp49p5N7HLPv/arAZjYz
            NagdnWJ8j47K51Sl9dHROilRHGymQADG9pFgGNtOSeH8xR4ikuVIHpCPhHDnJfEm
            nvIrEzpT7q3nBrWDzIHvG+9/HjDbqxtAP0pdYMRoKZ6g7jJR1ZhHoPbreW7zsY7B
            o1qm34qsVQkMV2WbwMRopL1H/fnKjEO6E/B7o4Lp85eXFNBL0qRil2qZJ5VHx0y0
            wYaHQ7S6OMYE6c7CWO3k4wv8MEqIbBuOoxGWl9J8YCbfQt5TkOi3iFnzeqfLqM5j
            5Jif7QACauRMsmuCbMXRqOT281uNjI/p5lJKik4fTF/DFgRbVleaMYC625j9lGmR
            zH99R0p9vneN5UiMG9GV1nLwShAO2pM0uBUUCENo+VJyy4VQKOzg6TSdrUVk8ilK
            fF43wpeN2MWgMa4p+qJT1TEADRa/nC5GvMd8jKM+ze/0eH84UIb8gRA+StgcEajS
            XgH/4Dxsl1+AsLAfUXCar3EjwPrU/HWO45NtkDzb5o7vrIshedOXXU7Aksn6lmcX
            lgRRY5QNlBrYqLOERGf9ZgrElLTb8bpMsi+dNFI823b1MgpG0hRG+3Q5sRCDgeQ=
            =hOw5
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
