auth:
    secretName: ENC[AES256_GCM,data:7NFBYMpWNfnMbEs=,iv:dvz1LB04V3x1/wtp/2Qbe8mma3nzJpiq96e7mbDLZrk=,tag:QcqwtGyEapmxFaQj+waa7w==,type:str]
    data: ENC[AES256_GCM,data:rXSDJgEQvRLDst4+v972bvI0sMtOcNzzUq4ju88c3+JshoN+dA2LQ7zkQw==,iv:3SEw8zWBzq35R6//+Xf0yIbvRVX4P5tMKQ70OltMVpo=,tag:WuwQZEjXnUfunbdVpeHhVw==,type:str]
env:
    CLIENT_ID: ENC[AES256_GCM,data:3+JuaZgnOgObzZNdwkQoYgrXec9rre3tl91WW7rIkRozo/1t,iv:zy6h2a75qarTemyMhzyTI7BzkWZi7N+wsc54RQEBX3k=,tag:VZ3OC9RNkAPjrIGSJkXLRw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:o0X+oo9sfazwpu0p8nPIS+fd98tvD4HPrS6gOV7kmb9VHFXPpycbwh2SvrsMbRlfwQW/RmpasmFrkM6l2XfC7w==,iv:foUQ2fDPZiCr8Fbb7EQ8gBNSlJ4ndk4bmco0sYWeuNI=,tag:6QierSxMmTHJTP2k+TCgaQ==,type:str]
    SQLALCHEMY_DATABASE_URI: ENC[AES256_GCM,data:ynNMszScFzc/BxlMMESp0PfIAwOFEzBIYSY+2Pn918g9eNHo3FvTfh9QkKuP7K7MBF44kpNvVSCdjKLrvhSgwkW0LCCPVOUK0m/Po4ZMXb120LhPbeHodKzPpx6f3afr6q4MPv0hu2h1AFHMDah2q4MfXM9QoR/mqNna4GIMRg==,iv:EGnlSHHppyt+1YmJkvGObeu20FYMTimUARyh6AH1Euc=,tag:SMhwuATzJPEbE4eBXytAEw==,type:str]
sops:
    lastmodified: "2026-01-25T17:56:06Z"
    mac: ENC[AES256_GCM,data:xCYAaUSyOWT+GUTm0JAnhMhQxHxZJjb/MWITQxPZLxJKw/0EY1lEW/tfxM/OKeiGYjVPRjUtoeNaTH79EoTAuJWz41zVvcqggTz/3W2TdsgBSUTh5aOfZgPlwtZT0Mn5UKBdBEmHiPQcOhn+45XVVBdiGVFNEeFExThggYq5/Qo=,iv:RDfKH8ORHMlV5llifAt3sFXGaB34GA8yDabkASW1m5M=,tag:6k/o40zFNvDlwO69RLqngQ==,type:str]
    pgp:
        - created_at: "2025-11-28T09:12:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ/+J6ZySsqukzgqJ2idFMqQ8XAzS3i19y4S5JuSlxChWOEY
            cpFesgM8kD/STnRVUG00I5eYViZLViLuU28Ziikbi4gA22dhu6wh1cX2Gzm1bGdx
            69xUIW2ZYF+6hdF6bM24FYTMkqdnrPd9nF1B1CCWxuHMIXPzPOpOiNDuHANXDeKT
            5bLhUVnNEouVlrzX/s6+s5CISNfohgKqYz0jU/ewfPde3X+Y+OvguJZ1G/FgSU/j
            No2McnsCWzHoqiGrLLaytN3HgkRGcEpl3uZheDBLIKQCa2Gic3gUy8wIrBDgk8lb
            wxXKxUYUQXYKlC8VfWVndTxEkEDgZVrI0UHrFGaFyEUQaULdWuV5FAyEckwhz679
            6Dyy0cLO8vuwzvjauFA44cN4ytSNHqNTaVD35wLOnHvKCaLFuSDspYyPnmbFuenU
            Zn8BwKnJOC301IOsDqO3/BhNjF/zRS266JketwAxdpsjsUvooPiNYt5ELSgQ/PiX
            H+7ZOErGB2NeiIjD8IcQCRY+zyCUy5q7KebbxSLGKwFo5Pq/QKSGd/8FsDgI6Ovd
            Ys7olAU28g89Mmd7sXmF4iQw/c12HghXS5XosrosjoH48QQtJ37YFSjFcE5XJ/ZQ
            ksBC4zTYRVtXIcqUsrPI4Ynz20HHwkelspppmxX9pCIn/YXvkwQLLRDQagJ1zLrS
            XAEHlD+CgMjBUGquV9tgktCxgvYl5hd6btqMUZy6JuP0b71pLsaeZ2HHR4FRSLEi
            9MswAgpHa6llVECpam62dmt21Lkz7mibX67DDf/Uy+sT7FPZCduFJmGsspG7
            =IgBn
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
