replicaCount: ENC[AES256_GCM,data:7A==,iv:nt2kCjdeZq9UA2UfsDegKHjGpz0vHkU9LlxkgUOkrFo=,tag:Gdbqp91arao9Y3sSQ6L85g==,type:int]
image:
    repository: ENC[AES256_GCM,data:a1BQazhYVYjWsrGOlCpA,iv:3ph1Gjbn7tN6vCKSn+rD2zGgu5NPdiel7dMF9zyQ8Uc=,tag:x1rxrQ4gvX+ZsJbP8U8ycw==,type:str]
    pullPolicy: ENC[AES256_GCM,data:I84C8PjV,iv:+SyEvcAfnOPrIhLVHfEmfubJ4A7RECKBg5qpOHVDwU0=,tag:a44qDh2LxUWLEEbcguzc/w==,type:str]
    tag: ENC[AES256_GCM,data:9rDzr3Q=,iv:OXmj7lQkXDSXHd+aZkZ36OXGckaD9j0yPVORn0STTvQ=,tag:yR3ZFNN34BiQgSLzRZl4gg==,type:str]
service:
    type: ENC[AES256_GCM,data:qF1YoSkXhjGi,iv:Vv1i9Bxv8oiA8CsenpFgu0+cJtW73GRq5NyzFvNS3vc=,tag:RzHcz9g7KKpPby5NxnQAUg==,type:str]
    port: ENC[AES256_GCM,data:BqYozA==,iv:5dpsffVcRxO3kFUpDeuu3jIrxk0yw5JfK9FhAqy1DvA=,tag:g9JrQbnW0MeovQq9fqbOCw==,type:int]
ingress:
    enabled: ENC[AES256_GCM,data:93aV/Q==,iv:ViMmQK82yk/JE4kzMP4AJy1NJVzKl3F9e+DwcvO+VDI=,tag:v1Pf8ou1LKolSTWbqnpTbg==,type:bool]
    className: ENC[AES256_GCM,data:wJp2/YI=,iv:xCOComVbn1VGUWM/AkMscgKUDesUtHAZjVs70e+eM8o=,tag:ZNfzQgBfmlswihnCv5KkEA==,type:str]
    host: ENC[AES256_GCM,data:glrbdxq+bzr/toeb9MzIzw==,iv:BVjTrm3NqpsM5kKfud5otwEu+298SHN5qmP7d94dDI0=,tag:So0bC1As1OiOEwrZ0j8WBg==,type:str]
    tls: ENC[AES256_GCM,data:Bk85JA==,iv:DF5/GxUlteqU8iD3FS/VH6T7VvsLaWwCwzsQ9LizbZs=,tag:35bxXyfzWxGid7OUoj8eqw==,type:bool]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:3mvWET/we06my7YQv7UhNg==,iv:b2yeb2XU4tgj0HSEVCI/TkpJJbJF/1IM/AaXDLtrDt4=,tag:vjIab3eP1oOuGa5O6Y2PDA==,type:str]
        nginx.ingress.kubernetes.io/auth-realm: ENC[AES256_GCM,data:nYD9YzdhGAghpo2hGsbrWiTW4EUD50M=,iv:yAeTQpfrVG4a3Dh62age9OlAy719BP8rKy13xi3kmX8=,tag:mJwtIc+Kx+e+0eHcx2XNaA==,type:str]
        nginx.ingress.kubernetes.io/auth-type: ENC[AES256_GCM,data:a0OCLak=,iv:HinTSYraP2C7vl1Mve6PjgjxpmvBxnX2RN8hGaeS+RY=,tag:4dEd/5HJ0FEmHIFzXHcWNw==,type:str]
        nginx.ingress.kubernetes.io/ssl-redirect: ENC[AES256_GCM,data:tk1WUw==,iv:KHBnUTcNl8ue3U6W2zUfkfQ2ZDxyyWokTw6mjIjjyUY=,tag:G5m1G7w8OWADGtGps0hZuA==,type:str]
        nginx.ingress.kubernetes.io/auth-secret: ENC[AES256_GCM,data:EBRlxsha6W52saE=,iv:2rZ1ilrlNxSYUSUU+AU9o8MorPzGDzVh1Le/SPVRl7A=,tag:9+R5+WR95PBWNgv7+lgrZg==,type:str]
auth:
    secretName: ENC[AES256_GCM,data:7NFBYMpWNfnMbEs=,iv:dvz1LB04V3x1/wtp/2Qbe8mma3nzJpiq96e7mbDLZrk=,tag:QcqwtGyEapmxFaQj+waa7w==,type:str]
    data: ENC[AES256_GCM,data:rXSDJgEQvRLDst4+v972bvI0sMtOcNzzUq4ju88c3+JshoN+dA2LQ7zkQw==,iv:3SEw8zWBzq35R6//+Xf0yIbvRVX4P5tMKQ70OltMVpo=,tag:WuwQZEjXnUfunbdVpeHhVw==,type:str]
env:
    CLIENT_ID: ENC[AES256_GCM,data:3+JuaZgnOgObzZNdwkQoYgrXec9rre3tl91WW7rIkRozo/1t,iv:zy6h2a75qarTemyMhzyTI7BzkWZi7N+wsc54RQEBX3k=,tag:VZ3OC9RNkAPjrIGSJkXLRw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:o0X+oo9sfazwpu0p8nPIS+fd98tvD4HPrS6gOV7kmb9VHFXPpycbwh2SvrsMbRlfwQW/RmpasmFrkM6l2XfC7w==,iv:foUQ2fDPZiCr8Fbb7EQ8gBNSlJ4ndk4bmco0sYWeuNI=,tag:6QierSxMmTHJTP2k+TCgaQ==,type:str]
    SQLALCHEMY_DATABASE_URI: ENC[AES256_GCM,data:ynNMszScFzc/BxlMMESp0PfIAwOFEzBIYSY+2Pn918g9eNHo3FvTfh9QkKuP7K7MBF44kpNvVSCdjKLrvhSgwkW0LCCPVOUK0m/Po4ZMXb120LhPbeHodKzPpx6f3afr6q4MPv0hu2h1AFHMDah2q4MfXM9QoR/mqNna4GIMRg==,iv:EGnlSHHppyt+1YmJkvGObeu20FYMTimUARyh6AH1Euc=,tag:SMhwuATzJPEbE4eBXytAEw==,type:str]
sops:
    lastmodified: "2025-11-30T12:41:36Z"
    mac: ENC[AES256_GCM,data:IGrQ9Z+r7iR4LWCbLUzlzzr74z518dz4j1DvVqxN8GEADUJplItd5eXhHQwe/6E4Hw9CdUQICtMKeVzVx+hxju9O+ve6e2Not+7vFYvCPoui2yCc6xSjoryvjjKeT+5jbwG3h/85o3FgVcxeMkiZFnZ/KAtnqe+x4ZM5Yzf+KLY=,iv:IJzGUs+NCG4s7jYt2IxoOcNF6u4McrPbz0wnNg/tkaA=,tag:oEzCochOm4E/faU5f4Aatg==,type:str]
    pgp:
        - created_at: "2025-11-28T09:12:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ/+J6ZySsqukzgqJ2idFMqQ8XAzS3i19y4S5JuSlxChWOEY
            cpFesgM8kD/STnRVUG00I5eYViZLViLuU28Ziikbi4gA22dhu6wh1cX2Gzm1bGdx
            69xUIW2ZYF+6hdF6bM24FYTMkqdnrPd9nF1B1CCWxuHMIXPzPOpOiNDuHANXDeKT
            5bLhUVnNEouVlrzX/s6+s5CISNfohgKqYz0jU/ewfPde3X+Y+OvguJZ1G/FgSU/j
            No2McnsCWzHoqiGrLLaytN3HgkRGcEpl3uZheDBLIKQCa2Gic3gUy8wIrBDgk8lb
            wxXKxUYUQXYKlC8VfWVndTxEkEDgZVrI0UHrFGaFyEUQaULdWuV5FAyEckwhz679
            6Dyy0cLO8vuwzvjauFA44cN4ytSNHqNTaVD35wLOnHvKCaLFuSDspYyPnmbFuenU
            Zn8BwKnJOC301IOsDqO3/BhNjF/zRS266JketwAxdpsjsUvooPiNYt5ELSgQ/PiX
            H+7ZOErGB2NeiIjD8IcQCRY+zyCUy5q7KebbxSLGKwFo5Pq/QKSGd/8FsDgI6Ovd
            Ys7olAU28g89Mmd7sXmF4iQw/c12HghXS5XosrosjoH48QQtJ37YFSjFcE5XJ/ZQ
            ksBC4zTYRVtXIcqUsrPI4Ynz20HHwkelspppmxX9pCIn/YXvkwQLLRDQagJ1zLrS
            XAEHlD+CgMjBUGquV9tgktCxgvYl5hd6btqMUZy6JuP0b71pLsaeZ2HHR4FRSLEi
            9MswAgpHa6llVECpam62dmt21Lkz7mibX67DDf/Uy+sT7FPZCduFJmGsspG7
            =IgBn
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
